# Generated by Django 5.2.10 on 2026-04-01 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DictTypeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_show", models.BooleanField(default=True, verbose_name="是否显示")),
                ("orders", models.IntegerField(default=1, verbose_name="排序")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "delete_time",
                    models.DateTimeField(auto_now=True, verbose_name="删除时间"),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="备注"
                    ),
                ),
                (
                    "type_name",
                    models.CharField(max_length=100, verbose_name="类型名称"),
                ),
                (
                    "type_code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="类型编码"
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="状态")),
            ],
            options={
                "verbose_name": "字典类型",
                "verbose_name_plural": "字典类型",
                "db_table": "uric_dict_type",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="DictDataModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_show", models.BooleanField(default=True, verbose_name="是否显示")),
                ("orders", models.IntegerField(default=1, verbose_name="排序")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "delete_time",
                    models.DateTimeField(auto_now=True, verbose_name="删除时间"),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="备注"
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="显示标签")),
                ("value", models.CharField(max_length=100, verbose_name="字典值")),
                ("status", models.BooleanField(default=True, verbose_name="状态")),
                (
                    "dict_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dict.dicttypemodel",
                        verbose_name="字典类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "字典数据",
                "verbose_name_plural": "字典数据",
                "db_table": "uric_dict_data",
                "ordering": ["orders", "-created_time"],
            },
        ),
    ]
