# Generated by Django 5.2.10 on 2026-05-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dict", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dicttypemodel",
            name="status",
            field=models.CharField(max_length=10, verbose_name="状态"),
        ),
    ]
