# Generated by Django 5.2.10 on 2026-05-27 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dict", "0002_alter_dicttypemodel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dictdatamodel",
            name="dict_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dict_items",
                to="dict.dicttypemodel",
                verbose_name="字典类型",
            ),
        ),
    ]
