# Generated by Django 5.2.10 on 2026-06-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dict", "0003_alter_dictdatamodel_dict_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dicttypemodel",
            name="status",
            field=models.BooleanField(verbose_name="状态"),
        ),
    ]
