# Generated by Django 5.2.10 on 2026-06-10 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dict", "0004_alter_dicttypemodel_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dictdatamodel",
            name="status",
        ),
    ]
