# Generated by Django 5.2.10 on 2026-02-26 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeviceAttrModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        null=True,
                        verbose_name="名称/标题",
                    ),
                ),
                ("is_show", models.BooleanField(default=True, verbose_name="是否显示")),
                ("orders", models.IntegerField(default=1, verbose_name="排序")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="描述信息"
                    ),
                ),
                ("device_brand", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeviceCateModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        null=True,
                        verbose_name="名称/标题",
                    ),
                ),
                ("is_show", models.BooleanField(default=True, verbose_name="是否显示")),
                ("orders", models.IntegerField(default=1, verbose_name="排序")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="描述信息"
                    ),
                ),
                ("device_cate", models.CharField(max_length=100)),
                ("device_status", models.CharField(max_length=100)),
                ("device_num", models.IntegerField()),
            ],
            options={
                "db_table": "device_cate",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="DeviceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        null=True,
                        verbose_name="名称/标题",
                    ),
                ),
                ("is_show", models.BooleanField(default=True, verbose_name="是否显示")),
                ("orders", models.IntegerField(default=1, verbose_name="排序")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="描述信息"
                    ),
                ),
                ("device_name", models.CharField(max_length=100)),
                ("device_status", models.CharField(max_length=100)),
                (
                    "device_attr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="device.deviceattrmodel",
                    ),
                ),
                (
                    "device_cate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="device.devicecatemodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
