# Generated by Django 5.2.10 on 2026-05-28 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeviceAttrModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_show", models.BooleanField(default=True, verbose_name="是否显示")),
                ("orders", models.IntegerField(default=1, verbose_name="排序")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "delete_time",
                    models.DateTimeField(auto_now=True, verbose_name="删除时间"),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="备注"
                    ),
                ),
                (
                    "attr_status",
                    models.BooleanField(default=True, verbose_name="设备状态"),
                ),
                (
                    "attr_name",
                    models.CharField(max_length=100, verbose_name="属性名称"),
                ),
                ("attr_value", models.CharField(max_length=100, verbose_name="属性值")),
                ("p_attr", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "uric_device_attr",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="DeviceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_show", models.BooleanField(default=True, verbose_name="是否显示")),
                ("orders", models.IntegerField(default=1, verbose_name="排序")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "delete_time",
                    models.DateTimeField(auto_now=True, verbose_name="删除时间"),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="备注"
                    ),
                ),
                ("device_name", models.CharField(max_length=100)),
                ("device_status", models.CharField(max_length=100)),
                (
                    "device_attr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="device.deviceattrmodel",
                    ),
                ),
            ],
            options={
                "db_table": "uric_devices",
                "ordering": ["-created_time"],
            },
        ),
    ]
