# Generated by Django 5.2.10 on 2026-02-26 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deviceattrmodel",
            options={"ordering": ["-created_time"]},
        ),
        migrations.AlterModelOptions(
            name="devicemodel",
            options={"ordering": ["-created_time"]},
        ),
        migrations.AlterModelTable(
            name="deviceattrmodel",
            table="uric_device_attr",
        ),
        migrations.AlterModelTable(
            name="devicecatemodel",
            table="uric_device_cate",
        ),
        migrations.AlterModelTable(
            name="devicemodel",
            table="uric_devices",
        ),
    ]
