# Generated by Django 5.2.10 on 2026-06-04 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceRecordModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_show", models.BooleanField(default=True, verbose_name="是否显示")),
                ("orders", models.IntegerField(default=1, verbose_name="排序")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "delete_time",
                    models.DateTimeField(auto_now=True, verbose_name="删除时间"),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="备注"
                    ),
                ),
                ("user", models.CharField(db_comment="领用人", max_length=20)),
                ("opt", models.CharField(db_comment="操作", max_length=20)),
            ],
            options={
                "db_table": "uric_device_record",
                "ordering": ["-created_time"],
            },
        ),
        migrations.AddField(
            model_name="devicemodel",
            name="buy_in",
            field=models.DateField(blank=True, db_comment="采购日期", null=True),
        ),
        migrations.AddField(
            model_name="devicemodel",
            name="device_code",
            field=models.CharField(
                blank=True, db_comment="设备编号", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="devicemodel",
            name="device_pic",
            field=models.CharField(
                blank=True, db_comment="设备图片", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="devicemodel",
            name="device_type",
            field=models.CharField(
                blank=True, db_comment="设备类型", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="devicemodel",
            name="sn_pn",
            field=models.CharField(
                blank=True, db_comment="SN/PN", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="devicemodel",
            name="device_attr",
            field=models.ForeignKey(
                blank=True,
                db_comment="设备属性",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="device.deviceattrmodel",
            ),
        ),
        migrations.AlterField(
            model_name="devicemodel",
            name="device_name",
            field=models.CharField(
                blank=True, db_comment="设备名", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="devicemodel",
            name="device_status",
            field=models.CharField(
                blank=True, db_comment="设备状态", max_length=100, null=True
            ),
        ),
    ]
