# Generated by Django 5.2.10 on 2026-06-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0002_devicerecordmodel_devicemodel_buy_in_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicemodel",
            name="device_attr",
            field=models.CharField(
                blank=True, db_comment="设备属性", max_length=100, null=True
            ),
        ),
    ]
