# Generated by Django 5.2.10 on 2026-02-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0002_alter_deviceattrmodel_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deviceattrmodel",
            name="name",
        ),
        migrations.RemoveField(
            model_name="devicecatemodel",
            name="name",
        ),
        migrations.RemoveField(
            model_name="devicemodel",
            name="name",
        ),
        migrations.AddField(
            model_name="deviceattrmodel",
            name="delete_time",
            field=models.DateTimeField(auto_now=True, verbose_name="删除时间"),
        ),
        migrations.AddField(
            model_name="devicecatemodel",
            name="delete_time",
            field=models.DateTimeField(auto_now=True, verbose_name="删除时间"),
        ),
        migrations.AddField(
            model_name="devicemodel",
            name="delete_time",
            field=models.DateTimeField(auto_now=True, verbose_name="删除时间"),
        ),
    ]
