# Generated by Django 5.2.10 on 2026-02-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0003_remove_deviceattrmodel_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="devicecatemodel",
            name="device_num",
        ),
        migrations.AddField(
            model_name="deviceattrmodel",
            name="device_cpu",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deviceattrmodel",
            name="device_disk",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deviceattrmodel",
            name="device_id",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deviceattrmodel",
            name="device_memory",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="devicecatemodel",
            name="device_cate",
            field=models.CharField(max_length=100, verbose_name="设备类别"),
        ),
        migrations.AlterField(
            model_name="devicecatemodel",
            name="device_status",
            field=models.CharField(max_length=100, verbose_name="设备状态"),
        ),
    ]
