# Generated by Django 5.2.10 on 2026-05-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0004_remove_devicecatemodel_device_num_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceattrmodel",
            name="remark",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="备注"
            ),
        ),
        migrations.AlterField(
            model_name="devicecatemodel",
            name="device_status",
            field=models.BooleanField(verbose_name="设备状态"),
        ),
        migrations.AlterField(
            model_name="devicecatemodel",
            name="remark",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="备注"
            ),
        ),
        migrations.AlterField(
            model_name="devicemodel",
            name="remark",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="备注"
            ),
        ),
    ]
